- name: Download and extract archive
  hosts: localhost

  tasks:
    - name: Download archive
      get_url:
        url: "https://dlcdn.apache.org/kafka/4.1.1/kafka-4.1.1-src.tgz"
        dest: "/home/user/ansible/kafka.tgz"
        mode: '0644'

    - name: Create directory for extraction
      file:
        path: "/home/user/ansible/kafka"
        state: directory
        mode: '0755'

    - name: Extract archive
      unarchive:
        src: "/home/user/ansible/kafka.tgz"
        dest: "/home/user/ansible/kafka"
